# Generated by Django 4.0.6 on 2022-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_cap_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='Some cool amazin descrition'),
            preserve_default=False,
        ),
    ]
