# Generated by Django 4.0.6 on 2022-07-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_cost_alter_hotel_rooms_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='cost',
        ),
    ]
