# Generated by Django 4.0.6 on 2022-07-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_hotel_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_period',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_period2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_period3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='stop_period',
        ),
        migrations.RemoveField(
            model_name='room',
            name='stop_period2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='stop_period3',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('begin_res', models.DateField()),
                ('end_res', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
    ]
