# Generated by Django 4.0.6 on 2022-08-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_rooms_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='photo',
            field=models.FileField(upload_to='static/user_photo'),
        ),
    ]
