# Generated by Django 4.1 on 2022-09-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_reservation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
    ]
