# Generated by Django 4.1 on 2022-09-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_remove_reservation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
        migrations.AddField(
            model_name='reservation',
            name='cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.cost'),
            preserve_default=False,
        ),
    ]
